dart-lang/coverage

lib/src/resolver.dart
@cbracken , here's the patch resolving symbolic links.
(I'm not sure if the last one, `file://`, works... too bad there are't unit tests :( ). So we can cut that one...
=> resolve symbolic links in the Resolver

bin/collect_coverage.dart, lib/src/devtools.dart, pubspec.yaml
In Dart SDK 1.9.0, access to the VM Observatory via the Chromium remote debugging protocol is no longer supported, and replaced with a JSON-rpc websocket interface via the observatory port. This behaviour is consistent with the VM websocket interface.
This patch applies the old behaviour on pre-1.9.0 VMs and the websocket JSON-rpc protocol for 1.9.0 and later.
=> Support Dart VM >= 1.9.0 websocket observatory protocol.

CHANGELOG.md, bin/format_coverage.dart
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dart-lang/coverage/92)
=> No longer emit SDK coverage unless explicitly requested via --sdk-root.

lib/coverage.dart, test/collect_coverage_api_test.dart, test/test_all.dart
I had the impression `true` for `wait` should work here https://github.com/dart-lang/coverage/compare/master...bwu-dart-contributing:master#diff-43df7f33c6ee2745896deffe2f16bfb4R77 but it didn't. Maybe I just don't understand how this is supposed to work.
I created a new test file even though a lot of code is just duplicated.
I thought it would be too messy if I put it in the `collect_coverage_test` file as well.
Some tests in `collect_coverage_test.dart` also the test I added only works half of the time on my machine even with much higher timeout. 
I wasted half of this day trying to make this work in a package of mine (didn't work reliable with the code before or after #39)
The attached file is the test output (actually a .txt file but GitHub won't let me attach it this way).
=> expose lib/src/collect

CHANGELOG.md, lib/src/devtools.dart, pubspec.yaml
Call this urgent. We're broken on the latest VM release.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dart-lang/coverage/96)
=> Fix change of eventType -> kind in Dart 1.11-dev.0.5

bin/format_coverage.dart, lib/src/formatter.dart, test/lcov_test.dart
Currently there is no way to specify which files you actually want coverage on during the `collect_coverage` step. As a workaround, I've added a `report-on` option to the `format_coverage` that takes one or many paths specifying the files/directories for which coverage should actually be formatted and included in the final lcov report.
Example usage:
```
pub run coverage:format_coverage -l --package-root=packages -i coverage.json -o coverage.lcov --report-on=lib/
```
The `coverage.lcov` output will then only include coverage data for files within the `lib/` directory.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dart-lang/coverage/67)
=> Add option to restrict coverage breadth.

test/collect_coverage_test.dart
Between spawning processes, disk I/O, and use of isolates, this test is timing
out relatively frequently on slower hardware.
=> Increase timeout for parseCoverage test.

test/collect_coverage_test.dart
With the elimination of isolates in parseCoverage (30c1b9a), the longer timeout
is no longer needed for slower machines -- at least reasonable ones :)
=> Reduce parseCoverage timeout to default.

lib/src/collect.dart, test/collect_coverage_test.dart
These aren't returned in the scripts section of the source report. Note: such
ranges will likely not be part of the source report in future VM versions, at
which time this check could be eliminated and the minimum SDK version bumped.
=> Skip over evaluate:source ranges.

CHANGELOG.md, bin/format_coverage.dart, lib/src/resolver.dart, test/resolver_test.dart
For Dart build rules for Bazel. See http://bazel.io.
=> Support Bazel-style URI resolution in format_coverage.

CHANGELOG.md, lib/src/resolver.dart, test/resolver_test.dart
In case `/packages/` is not found in the URI, fall back to simply returning the
URL path.
=> Bazel: Resolve http(s) URIs that don't contain 'packages' path segment.

lib/src/formatter.dart, test/lcov_test.dart
The resulting LCOV file will use paths relative to this base path.
=> Add a basePath argument to the LCOV formatter

CHANGELOG.md, bin/format_coverage.dart
LCOV output script paths are emitted relative to this directory if specified or
as absolute paths, if not.
=> `format_coverage`: add `--base-directory` option.

CHANGELOG.md, bin/format_coverage.dart, lib/src/formatter.dart, test/lcov_test.dart
This allows pre-configured Formatter objects to be passed to APIs.
=> Extract format reportOn and basePath parameters to constructor

test/lcov_test.dart
As of Dart SDK 1.20.0, pub no longer creates a packages directory by
default, relying instead on package spec (.packages) files.
=> Migrate tests from packages dir to package spec

CHANGELOG.md, lib/src/run_and_collect.dart
In almost all cases, developers should be defaulting to checked mode
when running tests. This change brings behaviour in line with the
package:test default.
=> Default to checked mode in runAndCollect

bin/collect_coverage.dart
This is a temporary measure for backward compatibility until dependent
code has migrated to the --uri option.
=> Add back support for --host and --port options

CHANGELOG.md, pubspec.yaml
Support for method generics, which pacakge:coverage users, was
introduced in Dart SDK 1.21.0. Release notes:
https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#1210---2016-12-07
=> Increase SDK lower bound to >=1.21.0

test/collect_coverage_test.dart, test/run_and_collect_test.dart, test/test_files/test_app_isolate.dart
Adds a test to verify expected coverage is generated for a synchronous
function with two branches, only one of which is executed.
=> Test coverage for synchronous function call

test/collect_coverage_test.dart, test/run_and_collect_test.dart, test/test_files/test_app_isolate.dart
Adds a test to verify expected coverage is generated for an asynchronous
function with two branches, only one of which is executed.
Line 21 is currently marked coverable and not hit due to a VM bug. Once
https://github.com/dart-lang/sdk/issues/31222 is fixed and the new VM
released to stable, we should remove the test expectation for that line
and close https://github.com/dart-lang/coverage/issues/196.
=> Test coverage for async function call

test/collect_coverage_test.dart, test/run_and_collect_test.dart
This eliminates test coverage expectations for the closing brace of
async functions, which was previously emitted as coverable by the VM
service (it shimmed in completeError as a hidden token on the closing
brace). See: https://github.com/dart-lang/coverage/issues/196
As of https://dart-review.googlesource.com/c/sdk/+/16605, that issue is
resolved in the VM. This patch eliminates test code designed to break
when that change rolls out.
=> Closing braces on async functions are not coverable

test/collect_coverage_test.dart, test/run_and_collect_test.dart
In VM commit https://dart-review.googlesource.com/c/sdk/+/16684/2,
function definitions were marked as coverable to handle cases such as
the following:
int get meaningOfLifeTheUniverseAndEverything => 42;
=> Mark function definition as coverable

lib/src/collect.dart, lib/src/hitmap.dart, lib/src/resolver.dart, pubspec.yaml, test/collect_coverage_api_test.dart, test/lcov_test.dart, test/test_files/test_app_isolate.dart
These will become an arrow in Dart 2.0. See this bug for more context:
https://github.com/dart-lang/sdk/issues/29630
I also fixed a couple of unused variable warnings while I was at it.
I bumped the version number in the pubspec. This is technically a
potentially breaking change because the signatures of createHitmap() and
mergeHitmaps() are more precise now. The only code I could find calling
that was in flutter_tools and that seems to be happy with the change.
If you'd rather I keep the old version, let me know.
=> Fix warnings related to fuzzy arrows.

tool/travis.sh
This ensures we emit one line per test as opposed to overwriting results
in stdout with each pass.
=> Use the expanded test reporter

.travis.yml, CHANGELOG.md, analysis_options.yaml, bin/collect_coverage.dart, lib/src/hitmap.dart, lib/src/run_and_collect.dart, pubspec.yaml, test/collect_coverage_api_test.dart, test/collect_coverage_test.dart, test/lcov_test.dart, tool/travis.sh
This commit migrates package:coverage to Dart 2. If any further Dart 1
bugfixes are required, they will be made on a dart_1 branch and released
as 0.10.x patch releases.
=> Version 0.11.0: Migrate to Dart 2

lib/src/hitmap.dart
json.decode() returns a List<dynamic>, but the previous declaration
over-narrowed it to List<Map<String, dynamic>>. The coverage file format
is still expected to be a list of JSON maps, but we no longer declare
the local as narrowly.
=> Fix type mismatch error in parseCoverage

CHANGELOG.md, lib/src/run_and_collect.dart, test/collect_coverage_test.dart, test/run_and_collect_test.dart, test/test_util.dart
The --checked flag has been removed in Dart SDK 2.0.0-dev.64.1. This
changes the default for the `checked` parameter in runAndCollect() to
false. In Dart 2, checked mode is no longer necessary, since type checks
are done statically at compile time. Support for the --checked flag will
be removed in a future version of package:coverage.
=> Update tests for Dart SDK 2.0.0-dev.64.1

bin/format_coverage.dart, lib/src/collect.dart, lib/src/resolver.dart, lib/src/util.dart, pubspec.yaml, test/collect_coverage_test.dart, test/run_and_collect_test.dart
* Eliminate use of deprecated Dart 1 constants. 
* Update to more recent package:args.
* Update to dartfmt from 2.0.0-dev.65.0.
=> Minor type, formatting fixes for 2.0.0-dev.64.1

CHANGELOG.md
* Eliminate use of deprecated Dart 1 constants.
* Update to more recent package:args.
* Update to dartfmt from 2.0.0-dev.65.0.
=> Version 0.12.1 (#224)

.travis.yml
Tests were switched to dev branch prior to Dart 2.0 going stable in
order to ensure compatibility with Dart 2. Now that Dart 2 has gone
stable, migrate back to stable branch to avoid failures due to VM/SDK
bugs.
=> Run Travis CI tests on Dart stable branch

bin/format_coverage.dart, lib/src/formatter.dart
Generally, for-loops should be preferred over forEach() unless calling
an existing unary function.
See: https://www.dartlang.org/guides/language/effective-dart/usage#avoid-using-iterableforeach-with-a-function-literal
This is a minor usage cleanup; no changes to functionality.
=> Replace uses of forEach with for-in loops

bin/collect_coverage.dart, lib/src/formatter.dart, lib/src/resolver.dart
Fixes lint: sort_constructors_first (Sort constructor declarations
before other members).
=> Move constructor definitions to top of classes

README.md
Dartium was removed from the Dart SDK prior to Dart 2.0 and is no longer
a supported tool.
=> Eliminate Dartium-related instructions

bin/format_coverage.dart
Fixes #239.   Corrects a runtime type error when reading a directory of files.
=> Fix format_coverage type error

lib/src/collect.dart, test/collect_coverage_api_test.dart
If a null serviceUri is passed to the collect() function, throw
ArgumentError. Flutter's coverage collection infra previously had a bug
wherein a null observatory port URL was sometimes passed to this
function. This makes debugging such cases marginally easier.
Fixes #227.
=> Throw ArgumentError when null serviceUri specified

test/collect_coverage_api_test.dart
In order to ensure reproducible tests in collect_coverage_api_test.dart,
we need to ensure the test app on which we collect coverage has run to
completion before starting collection.
This patch changes the test coverage collection run to wait until all
isolates have run to completion and are in paused state before we begin
coverage collection.
The test app runs in a VM with the `--pause-isolates-on-exit` flag set,
which guarantees we don't clean up isolates that have exited, which
leaves the VM wedged until after we collect coverage and the collector
resumes all isolates (causing the test app to exit).
=> Wait for all isolates to pause in test runs

analysis_options.yaml, lib/src/formatter.dart, lib/src/resolver.dart, lib/src/run_and_collect.dart
Migrates the syntax introduced in Dart 2.0.0 for typedefs and optional
parameter default values. Adds lints to prevent regressions.
=> Migrate to Dart 2 typedefs and parameter defaults

CHANGELOG.md, lib/src/collect.dart
This disables websocket compression when connecting to the VM service
port. Since almost all invocations of coverage collection tools happen
over a loopback connection to localhost, websocket compression uses a
ton of CPU, which causes a performance hit rather than a performance
benefit.
=> Disable websocket compression on service port

CHANGELOG.md, bin/collect_coverage.dart, lib/src/collect.dart, lib/src/run_and_collect.dart, test/collect_coverage_api_test.dart, test/lcov_test.dart
Skips collecting coverage for VM scripts with URIs with scheme 'dart'.
There's a lot of this source, most users aren't interested in collecting
coverage for it, and those who do, can still get at it by passing the
`--include-dart` flag if they want it.
This cuts test runtime down to 36% of what it previously was.
=> Skip dart: sources by default

CHANGELOG.md, lib/src/collect.dart, pubspec.yaml
I'm not sure why the VM would return empty coverage information for a given range but it does in practice. Handle this situation so we don't randomly choke.
=> Handle null coverage range

.travis.yml, CHANGELOG.md, bin/collect_coverage.dart, lib/src/collect.dart, lib/src/run_and_collect.dart, pubspec.yaml, test/collect_coverage_api_test.dart, test/lcov_test.dart
- Add new option `--scope-output` which restricts coverage output
- This significantly improves performance when provided
- Add corresponding test
- Updated minimum sdk given the new service API call that only existed in `2.1.1+`
cc @jonahwilliams
=> Support scoped output

CHANGELOG.md, lib/src/collect.dart, pubspec.yaml
pkg:vm_service_lib is discontinued
Related to https://github.com/dart-lang/vm_service_drivers/issues/257
=> Migrated to pkg:vm_service

lib/src/collect.dart
includeDart was added in 67b8249 (#257) as a means of controlling
whether coverage is collected for `dart:` libraries and should generally
be defaulted to false. This adds documentation for the parameter.
=> Document includeDart parameter on collect()

lib/src/collect.dart
Document `scopedOutput` argument and also default the value.
Although we default `scopedOutput` where it matters I've decided to also default it within `collect()` to prevent any accidental future issues.
Closes https://github.com/dart-lang/coverage/issues/265
=> ScopedOutput fixes

pubspec.yaml
I noticed due to the recent update in test that coverage depends on a older version of vm_service where as test uses the latest.
One option, coverage could drop vm_service from pubspec.yaml and just depend on the transitive version used by test. If interest, I'll make that change to this PR.
=> Bump version of vm_service

test/collect_coverage_api_test.dart, test/collect_coverage_test.dart, test/run_and_collect_test.dart, test/test_files/test_app_isolate.dart
Constant declarations are evaluated during kernel compilation, not by
the VM. This patch adds a const to `test_app_isolate.dart` and verifies
that it doesn't appear in the coverage hitmap in
`collect_coverage_test.dart` and `run_and_collect_test.dart`.
=> Test that const decls are not marked coverable

CHANGELOG.md, pubspec.yaml
Tighten the dependency on the `vm_service` package from `>=1.0.0 <3.0.0`
down to `>=1.0.0 <2.1.2` in order to exclude version `2.1.2` which is
broken on the current stable Dart VM due to a missing SDK constraint in
its pubspec.yaml. The breakage was introduced in:
https://github.com/dart-lang/sdk/commit/9e636b5ab4de850fb19bc262e0686fdf14bfbfc0.
=> Version 0.13.3+2

CHANGELOG.md, pubspec.yaml
See https://github.com/dart-lang/sdk/commit/7a911ce3f1e945f2cbd1967c6109127e3acbab5a
Fixes https://github.com/dart-lang/coverage/issues/278
=> Loosen version restriction on package:vm_service now that crasher has been fixed

CHANGELOG.md, pubspec.yaml, test/run_and_collect_test.dart
A name based on what we are testing makes this more clear.
=> Rename a variable for clarity

lib/src/collect.dart
When last isolate paused at exit resumes, the application might exit, close the socket.
If that happens coverage tool should handle closed socket and complete resume requests.
=> Make resumeIsolate robust, resilient in the face of exiting application.

CHANGELOG.md, README.md, bin/format_coverage.dart, lib/src/hitmap.dart, lib/src/util.dart, pubspec.yaml, test/collect_coverage_test.dart, test/run_and_collect_test.dart, test/test_files/test_app_isolate.dart, test/util_test.dart, tool/travis.sh
Use // coverage:ignore-line to ignore one line.
Use // coverage:ignore-start and // coverage:ignore-end to ignore range of lines inclusive.
Use // coverage:ignore-file to ignore the whole file.
=> Add the ability to ignore lines from coverage depending on the comment

lib/src/formatter.dart, lib/src/hitmap.dart, lib/src/resolver.dart, lib/src/util.dart
Since this version does not support Dart 1.0, these imports are
unnecessary.
=> Remove unused dart:async imports

CHANGELOG.md, lib/src/collect.dart, pubspec.yaml
Closes https://github.com/dart-lang/coverage/issues/309
There was a race condition in our logic which was exacerbated by SDK version `2.10`. If no isolates had started, we wouldn't properly wait to collect coverage information.
=> Fix --wait-paused with no isolates

bin/format_coverage.dart
Since Dart 2.1, Future and Stream have been exported from dart:core
=> Remove unused dart:async import

bin/format_coverage.dart, bin/run_and_collect.dart, lib/src/resolver.dart, lib/src/run_and_collect.dart
`--package-root=` is discontinued in dart.
(https://github.com/dart-lang/sdk/issues/41197)
=> Remove packageRoot in run_and_collect

CHANGELOG.md, pubspec.yaml
Eliminates the `--package-root` option from both run_and_collect and
format_coverage commands, as well as from non-public API under lib/src.
Related patch #324 by @lukaslihotzki.
=> Prep to publish 0.15.0

CHANGELOG.md, pubspec.yaml
cc @pq 
Note that getting the latest `logging` is blocked on https://github.com/google/webkit_inspection_protocol.dart/pull/65.
=> update several deps to allow the latest stable

CHANGELOG.md, bin/collect_coverage.dart, bin/format_coverage.dart, lib/src/chrome.dart, lib/src/collect.dart, lib/src/formatter.dart, lib/src/hitmap.dart, lib/src/resolver.dart, lib/src/run_and_collect.dart, lib/src/util.dart, pubspec.yaml, test/chrome_test.dart, test/collect_coverage_api_test.dart, test/collect_coverage_test.dart, test/format_coverage_test.dart, test/lcov_test.dart, test/test_files/test_app.dart
I did not do large refactors for the most part here I left in existing assumptions which means a lot of `!` are added.
Note that the `_shouldIgnoreLine` private method was moved to a local method and the patterns around it changed a fair bit due to iterators changing with null safety (it previously relied on `current` being null and now uses the result of `moveNext`).
=> migrate to null safety

CHANGELOG.md, lib/src/chrome.dart, pubspec.yaml
This was an incorrect migration originally it looks like, the test package returns null in a few different cases and it was previously handled a bit weirdly (adding entries with a null key). Now these are explicitly skipped.
=> allow null to be returned from the Chrome sourceUriProvider

CHANGELOG.md, lib/src/hitmap.dart, pubspec.yaml, test/collect_coverage_test.dart
Update `createHitmap` to return a sorted hitmap which is required by the ignore line annotations.
=> Return a sorted hitmap

CHANGELOG.md, lib/src/collect.dart, pubspec.yaml, test/collect_coverage_api_test.dart, test/collect_coverage_test.dart
The report lines flag returns the line numbers directly in the source report, rather than the token positions. This lets us skip the extra RPC to get the token pos to line number mapping. In my benchmarks, this halved the time it takes to collect coverage.
We still have to get the script objects if function coverage was requested. So to make sure the RPC skipping flow is tested, I've updated some of the tests so that function coverage is tested separately.
=> Use the report lines flag

lib/src/collect.dart, test/collect_coverage_api_test.dart
Isolate groups were enabled by default in the Dart VM recently. The hit counters are shared between all isolates in the group, so this caused a regression where coverage hits were being double counted. This PR fixes that regression by only collecting coverage for the first isolate in each group. This should also give us a significant performance boost in multi-isolate programs.
=> Gather coverage once per isolate group

CHANGELOG.md, bin/format_coverage.dart, lib/coverage.dart, lib/src/chrome.dart, lib/src/collect.dart, lib/src/formatter.dart, lib/src/hitmap.dart, test/collect_coverage_test.dart, test/lcov_test.dart, test/run_and_collect_test.dart
There were 5 functions that were changed in a backwards incompatible way in #348: `createHitmap`, `mergeHitmaps`, `parseCoverage`, `toScriptCoverageJson`, and `Formatter.format`.
This change makes #348 backwards compatible by renaming those newer functions, and adding versions of all those functions with the same signature as before. Most of these legacy functions simply wrap the newer versions and convert the `HitMap` back to a `Map<int, int>`.
| Legacy | New |
| --- | --- |
| createHitmap | HitMap.parseJson |
| mergeHitmaps | FileHitMaps.merge |
| parseCoverage | HitMap.parseFiles |
| toScriptCoverageJson | deprecated, no replacement |
| Formatter | deprecated, no replacement |
| PrettyPrintFormatter | FileHitMapsFormatter.prettyPrint |
| LcovFormatter | FileHitMapsFormatter.formatLcov …
=> Change function coverage to be backwards compatible

README.md
The below command for activation is deprecated and should be replace with `dart pub`
```
$ pub global activate coverage
The top level `pub` command is deprecated. Use `dart pub` instead.
```
This PR updates the README to use 
```
dart pub global activate coverage
```
=> Updates readme to use `dart pub`over `pub`

CHANGELOG.md, README.md, lib/src/run_and_collect.dart, lib/src/util.dart, test/collect_coverage_api_test.dart, test/collect_coverage_test.dart, test/lcov_test.dart, test/util_test.dart
"Observatory listening on..." is eventually being updated to "Dart VM
Service listening on...". This change allows for parsing the VM service
URI from messages of either format.
See https://github.com/dart-lang/sdk/issues/46756
=> Handle new VM service message format

CHANGELOG.md, README.md, bin/collect_coverage.dart, bin/format_coverage.dart, lib/src/collect.dart, lib/src/formatter.dart, lib/src/hitmap.dart, lib/src/run_and_collect.dart, pubspec.yaml, test/collect_coverage_api_test.dart, test/collect_coverage_test.dart, test/lcov_test.dart, test/run_and_collect_test.dart, test/test_util.dart
Implement branch coverage, using the new branch coverage source report from the VM service API.
To collect branch coverage information, pass `--branch-coverage` to *both* collect_coverage and the Dart command you're gathering coverage from. Branch coverage information can be pretty printed or included in lcov info. You'll also need a very recent version of the VM (service API v3.56, Dart VM v2.17).
Fixes #141
=> Branch coverage

test/collect_coverage_test.dart, test/lcov_test.dart, tool/test_and_collect.sh
Migrate tests to package_config.json, because .packages is doing away. The resolver still supports both .packages and package_config.json, and resolver_test.dart still tests both cases, for backwards compatibility.
#367
=> Migrate tests to package_config.json

CHANGELOG.md, lib/src/resolver.dart, test/resolver_test.dart
When running `flutter test --coverage` on windows, we noticed that forcing package:coverage to use the package_config.json file would lead to errors like:
```
00:01 +1 -1: loading C:\Users\Jonah\flutter\examples\hello_world\test\hello_test.dart [E]
Invalid argument(s): Uri c:/lib/ must have scheme 'file:'.
package:path/src/style/windows.dart 86:7                       WindowsStyle.pathFromUri
package:path/src/context.dart 1000:32                          Context.fromUri
package:path/path.dart 417:32                                  fromUri
package:coverage/src/resolver.dart 68:29                       Resolver.resolve
package:coverage/src/hitmap.dart 60:31                         HitMap.parseJson
===== asynchronous gap =========================== …
```
=> correctly parse package_config files on windows with relative root URI

.github/workflows/test-package.yml, CHANGELOG.md, bin/test_with_coverage.dart, lib/src/formatter.dart, pubspec.yaml, test/chrome_test.dart, test/test_with_coverage_test.dart, test/util_test.dart
Fixes:
- Increase timeout on the retry test, because it was timing out on mac CI
- Don't listen to SIGTERM on windows, in test_with_coverage
- Fix a path filter bug on windows, to do with \ vs / path separators
- Fix a bug in test_with_coverage_test that only shows up in windows, where incorrect flags were passed to pub
- Skip chrome_test on windows (#388)
Fixes #384
Fixes #385
=> Enable and fix mac and windows CI

test/collect_coverage_test.dart
The Dart VM fix for the CI failures also means that some branch coverage cases are no longer skipped. So we get an extra branch hit in this test.
Fixes #392
=> Fix branch coverage test

CHANGELOG.md, lib/src/hitmap.dart, lib/src/resolver.dart, pubspec.yaml, test/run_and_collect_test.dart
When checkIgnoredLines is true parseJson reads files to find
ignore data for that file.
If calling parseJson several times for the same project,
as for instance done in flutter, this adds significant overhead.
This commit adds a new function - parseJsonSync - which is passed
a cache of the lookups. This way future lookups for the same
file will be faster. The new function is also sync avoiding any
potential race conditions when filling up the cache.
This - in combination with a change on the Flutter side -
reduces the overhead of collecting coverage in Flutter.
On my machine running `flutter test --coverage` in `flutter/packages/flutter`
goes from ~13.5 minutes to ~10 minutes.
=> Add version of parseJson that can cache file reads and parses

lib/src/collect.dart, test/function_coverage_test.dart
The current logic looks up the script's library, then looks up all the functions in the library, and assumes that all those functions are in the script. But part files break this assumption.
So instead we have to look up the library, then for each of its functions, look up the corresponding script, and insert the function into that script's hitmap. Caching means that this isn't any slower.
Fixes #399
=> Fix handling of part files in function coverage

CHANGELOG.md, lib/src/util.dart, pubspec.yaml, test/test_files/test_app_isolate.dart, test/util_test.dart
This fixes #413, without the hassle of actually parsing all the strings (downside of this simple fix is that it's still possible for this bug to happen in multi-line strings). Before this, `print('// coverage:ignore-file');` would disable coverage for the file.
The fix is basically to make sure the line ends with the comment, rather than just containing it. But if I just used String.endsWith, then you'd end up with some very hard to debug errors:
```dart
// One of these is invalid:
// coverage:ignore-file
// coverage:ignore-file     
```
So instead I'm using regexps like `r'// coverage:ignore-file\s*$'`, to allow trailing white-space.
=> ignore-line comments etc must be at the end of the line

CHANGELOG.md, lib/src/hitmap.dart, lib/src/util.dart, test/util_test.dart
Adds some enhancements to ignore comment handling:
1. allow omitting space between `//` and `coverage` in coverage ignore comments
2. allow text after coverage ignore comments
3. throw `FormatException` when encountering unbalanced ignore comments instead of silently erroring
Hopefully 1 and 2 are uncontroversial.
3 did change an existing test.
We found it quite confusing in our projects when seemingly ignored lines were still appearing as uncovered.
Only after much investigation would various devs discover that it was due to accidental nesting of ignore ranges.
To my mind, the coverage tool should lean towards being permissive (or maybe hard fail?). 
Potentially an analyzer rule could be added to detect unbalanced coverage ignore comments.
---
<details>
<summary>Contribution …
=> Ignore enhancements

.github/workflows/test-package.yml, CHANGELOG.md, lib/src/collect.dart, pubspec.yaml, test/collect_coverage_api_test.dart, test/collect_coverage_mock_test.dart
`coverableLineCache` is a map from library URI to the set of all lines that are coverable. If users are doing multiple `collect` calls over the same set of libraries, they should pass an empty map to this param in the first call, and then pass the same map to all subsequent calls.
If `coverableLineCache` is provided, we set `VmService.getSourceReport`'s `librariesAlreadyCompiled` param to all its keys. This disables forced compilation for each of these libraries. The effect of this is that no misses are returned in the response for these libraries (and coverage collection is faster). To fill in the missing misses, we use the values of the `coverableLineCache` map. Finally, we fill this cache with all the hit and missed lines we've seen for each library.
So `coverableLineCache` caches all …
=> Add `coverableLineCache` param to `collect`

CHANGELOG.md, bin/test_with_coverage.dart, pubspec.yaml
test_with_coverage is a wrapper around collect_coverage and format_coverage that sets sensible defaults for all their flags that are designed to cover 99% of the coverage use cases. I have a couple of coverage collection scripts in dart-lang/native that only exist because they need to customize the value of the `--scope-output` flag that's passed to collect_coverage. Seems reasonable to just expose the flag in test_with_coverage.
https://github.com/dart-lang/native/issues/1120
=> Copy collect_coverage's `--scope-output` flag to test_with_coverage.

.github/workflows/test-package.yml
The VM service times out on Windows on SDKs before 3.5.
See https://github.com/dart-lang/coverage/issues/490
=> Exclude windows + Dart 3.4 from CI

CHANGELOG.md, lib/src/collect.dart, test/collect_coverage_mock_test.dart
The `--scope-output` filters are passed to `getSourceReport.libraryFilters`, but there are cases where the report can contain ranges that bypass the filter. This happens when the range has a different library than their enclosing function/class (eg mixins).
To fix this we just need to re-apply the filters to the reported ranges. It's still important to pass the filters to `getSourceReport`, because these are pretty rare edge cases and the filtering is still a useful optimisation to reduce the size of the report.
Fixes #495
=> Apply `--scope-output` filters after `getSourceReport`
