dart-lang/coverage

CHANGELOG.md

fixed format of changelog

---

lib/src/devtools.dart

Handle VM 1.11.0 observatory protocol change.

---

CHANGELOG.md
bin/format_coverage.dart
lib/src/hitmap.dart
pubspec.yaml
test/collect_coverage_test.dart
test/test_files/test_app.dart
test/test_files/test_app_isolate.dart

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dart-lang/coverage/74)

Testing createHitmap

---

CHANGELOG.md
lib/src/formatter.dart
lib/src/resolver.dart
pubspec.yaml
test/collect_coverage_test.dart
test/lcov_test.dart
test/test_files/test_app.dart
test/test_files/test_app_isolate.dart

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dart-lang/coverage/76)

tests, tweaks, optimizations

---

bin/format_coverage.dart

Addresses #75 for format_coverage.dart
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dart-lang/coverage/79)

Migrate format_coverage to async-await.

---

bin/collect_coverage.dart

Addresses #75 for collect_coverage.dart.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dart-lang/coverage/78)

Migrate collect_coverage to async-await.

---

lib/src/util.dart
test/lcov_test.dart
test/test_all.dart
test/util_test.dart
tool/travis.sh

Alternative to https://github.com/dart-lang/coverage/pull/83
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dart-lang/coverage/84)

rewrite retry, updated tests for travis

---

tool/travis.sh

Until https://github.com/duse-io/dart-coveralls/pull/32 lands
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dart-lang/coverage/86)

use Kevin's in-progress coveralls package to fix coverage reporting

---

bin/collect_coverage.dart
lib/src/devtools.dart
pubspec.yaml
test/collect_coverage_test.dart
tool/travis.sh

Along with a bunch of other cleanup
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dart-lang/coverage/89)

Support the latest service API in 1.11-dev.3

---

CHANGELOG.md
bin/collect_coverage.dart
lib/src/collect.dart
lib/src/resolver.dart
lib/src/util.dart
pubspec.yaml
test/collect_coverage_test.dart
test/lcov_test.dart
test/test_files/test_app_isolate.dart
test/util_test.dart

Cool?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dart-lang/coverage/93)

Final tweaks before 0.7.0 release

---

.gitignore
CHANGELOG.md
bin/format_coverage.dart
lib/src/formatter.dart
pubspec.yaml
test/lcov_test.dart

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dart-lang/coverage/97)

Updates following last pull request

---

CHANGELOG.md
lib/coverage.dart
lib/src/collect.dart
lib/src/run_and_collect.dart
lib/src/util.dart
test/collect_coverage_api_test.dart
test/collect_coverage_test.dart
test/run_and_collect_test.dart
test/test_all.dart
test/test_util.dart

This is progress towards https://github.com/dart-lang/coverage/issues/36
Just need to add in the entry point the bin
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dart-lang/coverage/95)

Adding runAndCollect

---

lib/src/hitmap.dart

Isolates were a useful performance booster when VM coverage was collected via
the `--coverage-dir` VM flag and potentially large numbers of coverage JSON
files needed to be parsed. With the elimination of that flag in 1.16, coverage
is always emitted to a single JSON file. This change also significantly
simplifies the code.

Eliminate use of isolates in parseCoverage.

---

lib/src/run_and_collect.dart

Added support for checked mode in `runAndCollect` function

---

AUTHORS

Adds a new author

---

CHANGELOG.md
analysis_options.yaml
bin/run_and_collect.dart
lib/src/collect.dart
pubspec.yaml
test/collect_coverage_api_test.dart
test/collect_coverage_test.dart
test/run_and_collect_test.dart

- fix some analysis issues (currently breaking the travis build)
- rename the analysis options file
- rev the sdk dep to `<2.0.0-dev.infinity`
@kevmoo, @cbracken

fix analysis issues; update sdk dep

---

bin/format_coverage.dart

Using dartfmt 1.0.7 from Dart SDK 1.25.0-dev.11.0.

Apply dartfmt - no behavioural changes

---

test/test_all.dart

coverage_test was being run twice.

Bugfix in tests_all: coverage_api test was not being run

---

bin/run_and_collect.dart
lib/coverage.dart
lib/src/formatter.dart
lib/src/hitmap.dart
lib/src/resolver.dart
test/resolver_test.dart
test/test_all.dart

Some files were missing copyright headers.

Add licence headers where missing

---

lib/coverage.dart
lib/src/collect.dart
lib/src/formatter.dart
lib/src/hitmap.dart
lib/src/resolver.dart
lib/src/run_and_collect.dart
lib/src/util.dart
test/collect_coverage_api_test.dart
test/collect_coverage_test.dart
test/lcov_test.dart
test/run_and_collect_test.dart
test/test_util.dart
test/util_test.dart

Remove library declarations

---

CHANGELOG.md
pubspec.yaml

Update package:args to 1.0.0

---

CHANGELOG.md
pubspec.yaml

update SDK version constraint.

---

lib/src/formatter.dart

Add number of instrumented lines 'LF' and number of lines with a non-zero execution count 'LH'

Enhance LCOV formatter.

---

analysis_options.yaml
bin/collect_coverage.dart
bin/format_coverage.dart
lib/src/collect.dart
lib/src/formatter.dart
lib/src/resolver.dart
lib/src/run_and_collect.dart
lib/src/util.dart
test/collect_coverage_api_test.dart
test/collect_coverage_test.dart
test/lcov_test.dart
test/resolver_test.dart
test/test_files/test_app.dart
test/test_files/test_app_isolate.dart
test/test_util.dart
test/util_test.dart

The new keyword was made optional in Dart 2.0.0 and is no longer
necessary.

Remove optional 'new' keyword

---

analysis_options.yaml
bin/collect_coverage.dart
bin/format_coverage.dart
bin/run_and_collect.dart
lib/src/collect.dart
lib/src/formatter.dart
lib/src/hitmap.dart
lib/src/resolver.dart
lib/src/run_and_collect.dart
lib/src/util.dart
test/collect_coverage_api_test.dart
test/collect_coverage_test.dart
test/lcov_test.dart
test/run_and_collect_test.dart
test/test_files/test_app.dart
test/test_files/test_app_isolate.dart
test/util_test.dart

This makes it easier to reason about the code. Enables the prefer_final_locals
lint.

Declare locals final where possible

---

CHANGELOG.md
lib/src/collect.dart
pubspec.yaml

vm_service_client is now abandonware. This migrates all VM service
lookups to package:vm_service_lib.

Migrate from vm_service_client to vm_service_lib

---

README.md

This should pervent users to face #249

Add --disable-service-auth-codes in README

---

CHANGELOG.md
lib/src/collect.dart
pubspec.yaml
test/collect_coverage_api_test.dart
test/lcov_test.dart
test/test_files/test_app.dart

Filter coverage by isolate ID

---

CHANGELOG.md
bin/format_coverage.dart
pubspec.yaml
test/format_coverage_test.dart
test/test_all.dart

Closes https://github.com/dart-lang/coverage/issues/272

Consider all json for format

---

test/collect_coverage_test.dart

Retry collect_coverage_test 3x

---

CHANGELOG.md
README.md
bin/format_coverage.dart
lib/src/hitmap.dart
lib/src/util.dart
pubspec.yaml
test/collect_coverage_test.dart
test/run_and_collect_test.dart
test/test_files/test_app_isolate.dart
test/util_test.dart
tool/travis.sh

See https://github.com/dart-lang/coverage/pull/304

Revert the 0.13.11 revert and properly model it as a breaking change

---

CHANGELOG.md

Version 0.14.2

---

CHANGELOG.md
lib/src/collect.dart
pubspec.yaml

Closes https://github.com/dart-lang/coverage/issues/321

Support latest package:vm_service

---

CHANGELOG.md
bin/format_coverage.dart
lib/src/hitmap.dart
pubspec.yaml
test/collect_coverage_api_test.dart
test/collect_coverage_test.dart
test/lcov_test.dart
test/run_and_collect_test.dart
test/test_files/test_app.dart

Closes https://github.com/dart-lang/coverage/issues/330

Pass packages argument to format_coverage

---

lib/src/util.dart
test/util_test.dart

See https://github.com/dart-lang/sdk/issues/46756

Change support for VM service message from "Dart VM Service listening" to "The Dart VM Service is listening"

---

lib/src/util.dart
test/util_test.dart

See https://github.com/dart-lang/sdk/issues/46756

Change support for VM service message from "The Dart VM Service is listening" to "The Dart VM service is listening"

---

CHANGELOG.md
pubspec.yaml

This is blocking https://github.com/flutter/flutter/pull/99677

Prepare for 1.2.0 release

---

bin/test_with_coverage.dart
lib/src/run_and_collect.dart
lib/src/util.dart
pubspec.yaml
test/collect_coverage_api_test.dart
test/collect_coverage_test.dart
test/function_coverage_test.dart
test/lcov_test.dart
test/test_with_coverage_test.dart

- test: use pkg:test_process
- DRY up logic for handling serviceUri

test cleanup

---

lib/src/run_and_collect.dart
lib/src/util.dart
test/collect_coverage_api_test.dart
test/collect_coverage_test.dart
test/function_coverage_test.dart
test/lcov_test.dart
test/test_util.dart

test: use TestProcess more places

---

CHANGELOG.md
bin/test_with_coverage.dart
lib/src/collect.dart
pubspec.yaml
test/test_with_coverage_package/lib/validate_lib.dart
test/test_with_coverage_package/pubspec.yaml
test/test_with_coverage_package/test/product_test.dart
test/test_with_coverage_package/test/sum_test.dart
test/test_with_coverage_test.dart

- Working on test_with_coverage
- cleanup collect
- cleanup: bin/test_with_coverage.dart
- Support passing extra arguments to test via test_with_coverage

i403 test argrs

---

CHANGELOG.md
README.md

Changelog: drop dates from releases - this info is on pub.dev

Format and cleanup markdown files

---

CHANGELOG.md
LICENSE
pubspec.yaml

- update the to standard Dart BSD license

update the to standard Dart BSD license

---

CHANGELOG.md
pubspec.yaml

update vm_service to allow vm_service:11.0.0

---

README.md

Close #474
- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.
---
<details>
<summary>Contribution guidelines:</summary><br>
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-ch …

Hint users how to let the ignore comments take effect

---

lib/src/chrome.dart

Blocking https://github.com/dart-lang/coverage/pull/483

Fix nullability analysis error
